import { router } from 'expo-router';
import React, {useEffect, useMemo, useState} from 'react';
import {ActivityIndicator, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Ionicons} from '@expo/vector-icons';
import Native, {LaunchableApp} from '@/modules/elraey-performance';
import {theme} from '@/constants/theme';

const CUSTOM_KEY='elraey.customGames.v1';
type Game=LaunchableApp & {custom?: boolean};

export default function Games(){
 const [apps,setApps]=useState<Game[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [modal,setModal]=useState(false); const [pkg,setPkg]=useState(''); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const detected=await Native.getLaunchableApps();const raw=await AsyncStorage.getItem(CUSTOM_KEY);const custom:Game[]=raw?JSON.parse(raw):[];const merged=[...detected,...custom.filter(c=>!detected.some(d=>d.packageName===c.packageName))];setApps(merged)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>apps.filter(a=>a.name.toLowerCase().includes(q.toLowerCase())||a.packageName.toLowerCase().includes(q.toLowerCase())),[apps,q]);
 const add=async()=>{const packageName=pkg.trim();if(!packageName){setError('Enter the game package name.');return}const exists=apps.find(a=>a.packageName===packageName);if(exists){setError('This game is already in your list.');return}const item:Game={packageName,name:packageName,isGame:true,custom:true};const raw=await AsyncStorage.getItem(CUSTOM_KEY);const custom:Game[]=raw?JSON.parse(raw):[];await AsyncStorage.setItem(CUSTOM_KEY,JSON.stringify([...custom,item]));setApps(x=>[...x,item]);setPkg('');setError('');setModal(false)};
 return <View style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20} color={theme.text}/></Pressable><Text style={s.title}>My Games</Text><Pressable onPress={()=>setModal(true)}><Ionicons name="add-circle-outline" size={25} color={theme.accent}/></Pressable></View><View style={s.search}><Ionicons name="search" size={18} color={theme.muted}/><TextInput value={q} onChangeText={setQ} placeholder="Search installed games & apps" placeholderTextColor="#64736D" style={s.input}/></View><Text style={s.note}>Detected {apps.length} launchable apps. Games are marked when Android identifies them.</Text>{loading?<ActivityIndicator color={theme.accent} style={{marginTop:30}}/>:<FlatList data={filtered} keyExtractor={x=>x.packageName} contentContainerStyle={{padding:18,paddingTop:8,paddingBottom:30}} renderItem={({item})=><Pressable style={s.item} onPress={()=>Native.launchApp(item.packageName)}><View style={s.gameIcon}><Ionicons name={item.isGame?'game-controller':'apps'} size={21} color={theme.accent}/></View><View style={{flex:1}}><Text style={s.name}>{item.name}</Text><Text style={s.package}>{item.packageName}{item.custom?' · CUSTOM':''}</Text></View><View style={s.play}><Ionicons name="play" size={14} color="#06100C"/></View></Pressable>}/>}<Modal visible={modal} transparent animationType="fade" onRequestClose={()=>setModal(false)}><View style={s.overlay}><View style={s.modal}><Text style={s.modalTitle}>Add Game</Text><Text style={s.modalHint}>Enter the Android package name, for example com.example.game</Text><TextInput value={pkg} onChangeText={x=>{setPkg(x);setError('')}} autoCapitalize="none" autoCorrect={false} placeholder="com.example.game" placeholderTextColor="#64736D" style={s.modalInput}/>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.modalRow}><Pressable style={s.cancel} onPress={()=>setModal(false)}><Text style={s.cancelText}>CANCEL</Text></Pressable><Pressable style={s.add} onPress={add}><Text style={s.addText}>ADD GAME</Text></Pressable></View></View></View></Modal></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg},header:{height:108,paddingTop:54,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:38},title:{color:theme.text,fontSize:24,fontWeight:'900'},search:{marginHorizontal:18,height:50,borderRadius:15,borderWidth:1,borderColor:theme.border,backgroundColor:theme.panel,flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:8},input:{flex:1,color:theme.text,fontSize:14},note:{color:theme.muted,fontSize:11,paddingHorizontal:20,paddingVertical:10},item:{backgroundColor:theme.panel,borderColor:theme.border,borderWidth:1,borderRadius:17,padding:12,flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},gameIcon:{width:44,height:44,borderRadius:13,backgroundColor:'#0D2118',alignItems:'center',justifyContent:'center'},name:{color:theme.text,fontSize:15,fontWeight:'800'},package:{color:theme.muted,fontSize:9,marginTop:3},play:{width:34,height:34,borderRadius:11,backgroundColor:theme.accent,alignItems:'center',justifyContent:'center'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.72)',justifyContent:'center',padding:20},modal:{backgroundColor:theme.panel,borderColor:theme.border,borderWidth:1,borderRadius:24,padding:20},modalTitle:{color:theme.text,fontSize:22,fontWeight:'900'},modalHint:{color:theme.muted,fontSize:12,lineHeight:18,marginTop:7},modalInput:{height:52,borderRadius:14,borderWidth:1,borderColor:theme.border,color:theme.text,paddingHorizontal:14,marginTop:16},error:{color:'#FF8C8C',fontSize:11,marginTop:8},modalRow:{flexDirection:'row',gap:9,marginTop:16},cancel:{flex:1,height:48,borderRadius:14,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},cancelText:{color:theme.text,fontWeight:'800',fontSize:11},add:{flex:1,height:48,borderRadius:14,backgroundColor:theme.accent,alignItems:'center',justifyContent:'center'},addText:{color:'#06100C',fontWeight:'900',fontSize:11}});
