import { router } from 'expo-router';
import React,{useEffect,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import Native from '@/modules/elraey-performance';
import {theme} from '@/constants/theme';
export default function Settings(){const [display,setDisplay]=useState<any>();const [overlay,setOverlay]=useState(false);useEffect(()=>{Native.getDisplayInfo().then(setDisplay);Native.canDrawOverlays().then(setOverlay).catch(()=>{})},[]);const max=Math.max(...(display?.supportedRefreshRates??[0]));return <ScrollView style={s.root} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={22} color={theme.text}/></Pressable><Text style={s.title}>Performance Settings</Text><View style={{width:22}}/></View><Text style={s.section}>DISPLAY</Text><Item icon="speedometer" title="Maximum supported refresh rate" detail={`${Math.round(max)} Hz`} action={max?()=>{Native.setPreferredRefreshRate(max);Native.getDisplayInfo().then(setDisplay)}:undefined}/><Item icon="settings" title="Android display settings" detail="System-level refresh-rate controls" action={()=>Native.openDisplaySettings()}/><Text style={s.section}>TOOLS</Text><Item icon="layers" title="Floating overlay permission" detail={overlay?'Granted':'Not granted'} action={()=>Native.openOverlaySettings()}/><Item icon="phone-portrait" title="App settings" detail="Android permissions and battery controls" action={()=>Native.openAppSettings()}/><Text style={s.section}>ABOUT</Text><View style={s.card}><Text style={s.name}>Elraey Performance</Text><Text style={s.muted}>Gaming performance toolkit · v1.0.0</Text><Text style={s.small}>Native metrics are reported only when Android exposes them. No fake FPS or fabricated hardware readings.</Text></View></ScrollView>}
function Item({icon,title,detail,action}:{icon:any;title:string;detail:string;action?:()=>void}){return <Pressable style={s.item} onPress={action} disabled={!action}><View style={s.icon}><Ionicons name={icon} size={19} color={theme.accent}/></View><View style={{flex:1}}><Text style={s.name}>{title}</Text><Text style={s.muted}>{detail}</Text></View>{action&&<Ionicons name="chevron-forward" size={18} color="#61706A"/>}</Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg},content:{padding:18,paddingTop:54,paddingBottom:40},header:{height:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:theme.text,fontSize:21,fontWeight:'900'},section:{color:theme.muted,fontSize:10,fontWeight:'900',letterSpacing:1.8,marginTop:24,marginBottom:9},item:{backgroundColor:theme.panel,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:13,flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},icon:{width:42,height:42,borderRadius:13,backgroundColor:'#0D2118',alignItems:'center',justifyContent:'center'},name:{color:theme.text,fontSize:14,fontWeight:'800'},muted:{color:theme.muted,fontSize:11,marginTop:3},card:{backgroundColor:theme.panel,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:18},small:{color:'#8D9C95',fontSize:11,lineHeight:17,marginTop:12}});
